# Random suffix to ensure unique workspace names for test runs
resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

# 1. Compliant Test Workspace
resource "terrakube_workspace_cli" "compliant" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}compliant-${random_string.suffix.result}"
  description     = "OPA test workspace for compliant plan evaluation"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 2. Advisory Warning Test Workspace
resource "terrakube_workspace_cli" "advisory" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}advisory-${random_string.suffix.result}"
  description     = "OPA test workspace demonstrating non-blocking advisory tagging warnings"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 3. Soft Mandatory Failure Test Workspace
resource "terrakube_workspace_cli" "soft_fail" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}soft-fail-${random_string.suffix.result}"
  description     = "OPA test workspace demonstrating blast radius soft mandatory override flow"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 4. Hard Mandatory Failure Test Workspace
resource "terrakube_workspace_cli" "hard_fail" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}hard-fail-${random_string.suffix.result}"
  description     = "OPA test workspace demonstrating hard mandatory blocking on unencrypted/public resources"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# Automatically generate backend.tf in each CLI test example folder
resource "local_file" "backend_compliant" {
  filename = "${path.module}/../examples/compliant-workspace/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.compliant.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_advisory" {
  filename = "${path.module}/../examples/advisory-warning-workspace/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.advisory.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_soft_fail" {
  filename = "${path.module}/../examples/soft-fail-workspace/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.soft_fail.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_hard_fail" {
  filename = "${path.module}/../examples/hard-fail-workspace/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.hard_fail.name}"
        }
      }
    }
  EOT
}
