# Random suffix to ensure unique workspace names for test runs
resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

# 1. Compliant Test Workspace
resource "terrakube_workspace_cli" "compliant" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}compliant-${random_string.suffix.result}"
  description     = "OPA test workspace for compliant plan evaluation"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 2. Advisory Warning Test Workspace
resource "terrakube_workspace_cli" "advisory" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}advisory-${random_string.suffix.result}"
  description     = "OPA test workspace demonstrating non-blocking advisory tagging warnings"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 3. Soft Mandatory Failure Test Workspace
resource "terrakube_workspace_cli" "soft_fail" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}soft-fail-${random_string.suffix.result}"
  description     = "OPA test workspace demonstrating blast radius soft mandatory override flow"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 4. Hard Mandatory Failure Test Workspace
resource "terrakube_workspace_cli" "hard_fail" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}hard-fail-${random_string.suffix.result}"
  description     = "OPA test workspace demonstrating hard mandatory blocking on unencrypted/public resources"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# Automatically generate backend.tf in each CLI test example folder
resource "local_file" "backend_compliant" {
  filename = "${path.module}/../examples/compliant-workspace/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.compliant.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_advisory" {
  filename = "${path.module}/../examples/advisory-warning-workspace/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.advisory.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_soft_fail" {
  filename = "${path.module}/../examples/soft-fail-workspace/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.soft_fail.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_hard_fail" {
  filename = "${path.module}/../examples/hard-fail-workspace/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.hard_fail.name}"
        }
      }
    }
  EOT
}

# ==============================================================================
# Cloud-Free Password Policy Test Workspaces
# ==============================================================================

# 5. Compliant Password Workspace (length >= 16)
resource "terrakube_workspace_cli" "password_compliant" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}pwd-compliant-${random_string.suffix.result}"
  description     = "Cloud-free OPA test workspace for compliant password evaluation (length >= 16)"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 6. Advisory Password Workspace (12 <= length < 16)
resource "terrakube_workspace_cli" "password_advisory" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}pwd-advisory-${random_string.suffix.result}"
  description     = "Cloud-free OPA test workspace demonstrating advisory password warning (12 <= length < 16)"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 7. Soft Mandatory Password Workspace (8 <= length < 12)
resource "terrakube_workspace_cli" "password_soft_fail" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}pwd-soft-fail-${random_string.suffix.result}"
  description     = "Cloud-free OPA test workspace demonstrating soft mandatory SecOps override flow (8 <= length < 12)"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# 8. Hard Mandatory Password Workspace (length < 8)
resource "terrakube_workspace_cli" "password_hard_fail" {
  organization_id = data.terrakube_organization.org.id
  name            = "${var.workspace_prefix}pwd-hard-fail-${random_string.suffix.result}"
  description     = "Cloud-free OPA test workspace demonstrating hard mandatory blocking on short passwords (length < 8)"
  execution_mode  = "remote"
  iac_type        = "terraform"
  iac_version     = var.iac_version
}

# Backend generation for Password Workspaces
resource "local_file" "backend_password_compliant" {
  filename = "${path.module}/../examples/password-compliant/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.password_compliant.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_password_advisory" {
  filename = "${path.module}/../examples/password-advisory/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.password_advisory.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_password_soft_fail" {
  filename = "${path.module}/../examples/password-soft-fail/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.password_soft_fail.name}"
        }
      }
    }
  EOT
}

resource "local_file" "backend_password_hard_fail" {
  filename = "${path.module}/../examples/password-hard-fail/backend.tf"
  content  = <<-EOT
    # Automatically generated by terrakube-governance
    terraform {
      cloud {
        hostname     = "${var.terrakube_hostname}"
        organization = "${var.organization_name}"
        workspaces {
          name = "${terrakube_workspace_cli.password_hard_fail.name}"
        }
      }
    }
  EOT
}
